version: "3"

services:
        backend:
                build:
                        context: ./backend/
                ports:
                        - "8080:8080"
                environment:
                        - DB_URI=api.db
                restart: unless-stopped
        frontend:
                build:
                        context: ./my-app
                ports:
                        - "3000:3000"
                command: serve -s /usr/src/app/build -l 3000
                depends_on:
                        - backend
                restart: unless-stopped
        nginx:
                build:
                        context: ./nginx/
                ports:
                        - "80:80"
                restart: unless-stopped


